---
name: Broadcast files to organization
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo_name:
        description: >-
          Target repo name.
          If empty all organization repos will be updated.
        required: false
permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: read
jobs:
  broadcast_files:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/broadcast-files.yml@main
    secrets:
      GH_ACCESS_TOKEN: '${{ secrets.GH_ACCESS_TOKEN }}'
