name: Pull Request Cleaner

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      org_name:
        description: GitHub organization name
        required: true
        default: 'Netcracker'
      branch_name_prefix:
        description: Prefix for branch names to target
        required: true
        default: 'bot/'
      branch_delete:
        description: Delete branches after closing PRs? (true/false)
        required: false
        default: 'true'
      remove_orphan_branches:
        description: Remove orphan branches with given prefix? (true/false)
        required: false
        default: 'false'
      target_repo:
        description: Specific repository to process (leave blank for all)
        required: false
        default: ''
      comment:
        description: Comment when closing PRs
        required: true
        default: 'This PR is closed as part of the cleanup process.'
      dry_run:
        description: Run without making changes? (true/false)
        required: false
        default: 'false'

jobs:
  pull_request_cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x .github/scripts/pr-cleaner.sh

      - name: Run Pull Request Cleaner
        run: |
          bash .github/scripts/pr-cleaner.sh \
            "${{ github.event.inputs.org_name }}" \
            "${{ github.event.inputs.branch_name_prefix }}" \
            "${{ github.event.inputs.branch_delete }}" \
            "${{ github.event.inputs.remove_orphan_branches }}" \
            "${{ github.event.inputs.target_repo }}" \
            "${{ github.event.inputs.comment }}" \
            "${{ secrets.GH_ACCESS_TOKEN }}" \
            "${{ github.event.inputs.dry_run }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
