name: Pull Request Cleaner

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      org_name:
        description: >-
          Name of GitHub organization.
        required: true
        default: 'Netcracker'
      branch_name_prefix:
        description: >-
          Prefix of the branch name to be deleted.
        required: true
        default: 'bot/'
      branch_delete:
        description: >-
          Whether to delete the branch after closing the PR.
          If true, the branch will be deleted.
        required: false
        default: 'true'
      remove_orphant_branches:
        description: >-
          Whether to remove orphan branches.
          If true, the branches not related to PRs will be removed.
        required: false
        default: 'false'
      target_repo:
        description: >-
          Name of the target repository.
          If empty all organization repos will be updated.
        required: false
      comment:
        description: >-
          Comment to be added when closing the PR.
        required: true
        default: 'This PR is closed as part of the cleanup process.'
jobs:
  pull_request_cleanup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2 Setup Pull Request Cleaner
      - name: Setup Pull Request Cleaner
        run: bash .github/scripts/pr-cleaner.sh \
          "${{ github.event.inputs.org_name }}" \
          "${{ github.event.inputs.branch_name_prefix }}" \
          "${{ github.event.inputs.branch_delete }}" \
          "${{ github.event.inputs.remove_orphant_branches }}" \
          "${{ github.event.inputs.target_repo }}" \
          "${{ github.event.inputs.comment }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
